AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/**/*'
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FirstParameterIndentation:
  Enabled: false

Rails:
  Enabled: true
