sudo: false
script:
  - bundle exec rspec
  - bundle exec rubocop
language: ruby
cache: bundler
before_install: gem install bundler

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

rvm:
  - 2.2

services:
  - postgresql

addons:
  code_climate:
    repo_token: 48e94452c54c2a971b4c62bb65a148015c1914ad3f68ba6eabacc10f8046fc06
